name: CI Build
on: [ push, pull_request ]

jobs:
  ci:
    name: Run Go Build, Tests and Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: nix develop --command go build -v ./...
      - name: Run Tests
        run: nix develop --command go test -v ./...
      - name: Lint
        run: nix develop --command golangci-lint run
